### ISSUE TITLE
Doesn't run on Mac OS

### ISSUE THREAD

**Issue by ghost** [AVturbine/mapmaker#1]
File "main.py", line 202
    json_struct = create_json(seed, width, height earth_terrain, earth_karbonite, bots, mars_terrain, mars_karbonite, asteroids, orbit_params)
                                                              ^
SyntaxError: invalid syntax

Specs: Python 3.5.2, Installed pygame

**Comment by tkanarsky** [comment]
Just took out that line break, believe it should work now.

**Comment by tkanarsky** [comment]
wait nvm i see it, there's not a comma rip

**Comment by tkanarsky** [comment]
just a second

**Comment by tkanarsky** [comment]
There, that should do it
